version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      # this is 8080 in prod
    ports:
      - "3000:3000"
      # comment below volumes in prod
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data: