name: Deploy to Google Cloud Run

on:
  push:
    branches: [security-checks]

jobs:
  deploy:
    name: GCP Deploy
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      GCP_CLIENT_ID: ${{ secrets.GCP_CLIENT_ID }}
      GCP_CLIENT_SECRET: ${{ secrets.GCP_CLIENT_SECRET }}
      GCP_AUTH_URI: ${{ secrets.GCP_AUTH_URI }}
      GCP_TOKEN_URI: ${{ secrets.GCP_TOKEN_URI }}
      GCP_REDIRECT_URI: ${{ secrets.GCP_REDIRECT_URI }}
      GCP_CALLBACK_REDIRECT_URI: ${{ secrets.GCP_CALLBACK_REDIRECT_URI }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SESSION_NAME: ${{ secrets.DB_SESSION_NAME }}
      ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          #TODO: workload identity federation
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}
          gcloud auth configure-docker --quiet

      - name: Build & Push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/scribbler-api .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/scribbler-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy scribbler-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/scribbler-api \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars="NODE_ENV=${NODE_ENV},ALLOWED_ORIGIN=${ALLOWED_ORIGIN},MONGODB_URI=${MONGODB_URI},SESSION_SECRET=${SESSION_SECRET},GCP_CLIENT_ID=${GCP_CLIENT_ID},GCP_CLIENT_SECRET=${GCP_CLIENT_SECRET},GCP_AUTH_URI=${GCP_AUTH_URI},GCP_TOKEN_URI=${GCP_TOKEN_URI},GCP_REDIRECT_URI=${GCP_REDIRECT_URI},GCP_CALLBACK_REDIRECT_URI=${GCP_CALLBACK_REDIRECT_URI},DB_NAME=${DB_NAME},DB_SESSION_NAME=${DB_SESSION_NAME}"
